name: pofk_algorithm
description: >
  A fast, extensible Dart library for algorithms and data structures, offering search, sort, and AI utilities. Over 500 algorithms planned in future versions.
license: MIT

version: 0.0.1
repository: https://github.com/POFKLabs/pofk_algorithm

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
